[package]
name = "eigenlog"
version = "0.1.0"
authors = ["Eric Sheppard <eric@sheppard.cloud>"]
edition = "2018"

[[bin]]
name = "server"
path = "server.rs"
required-features = ["server"]

[dependencies]
bincode = "1.3"
once_cell = "1.7"
regex = "1.5"
serde_json = "1"
thiserror = "1"
uuid = "0.8"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.log]
version = "0.4"
features = ["serde"]

[dependencies.futures]
version = "0.3"

[dependencies.reqwest]
version = "0.11"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sled]
version = "0.34"
optional = true 

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.ulid]
version = "0.4"
features = ["serde","uuid"]

[dependencies.warp]
version = "0.3"
optional = true

[features]
client = ["reqwest"]
server = ["sled", "warp"]
default = ["client", "server"]


